"""add messages table and user context fields

Revision ID: 0da268b50ed0
Revises: c9b0c269f5cf
Create Date: 2025-12-08 00:40:53.471075

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da268b50ed0'
down_revision: Union[str, Sequence[str], None] = 'c9b0c269f5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chat_context', 'messages', ['chat_id', 'context_id'], unique=False)
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('current_context_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('webhook_secret', sa.String(), nullable=True))

    # Populate existing users with UUIDs
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT chat_id FROM users")).fetchall()
    for (chat_id,) in users:
        connection.execute(
            sa.text("UPDATE users SET current_context_id = :ctx, webhook_secret = :secret WHERE chat_id = :chat_id"),
            {"ctx": str(uuid.uuid4()), "secret": str(uuid.uuid4()), "chat_id": chat_id}
        )

    # Create unique index instead of constraint (SQLite compatible)
    op.create_index('ix_users_webhook_secret', 'users', ['webhook_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_webhook_secret', table_name='users')
    op.drop_column('users', 'webhook_secret')
    op.drop_column('users', 'current_context_id')
    op.drop_index('ix_messages_chat_created', table_name='messages')
    op.drop_index('ix_messages_chat_context', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
